version: 2

jobs:
  build-and-test:
    docker:
      - image: circleci/node:8
        environment:
          NPM_CONFIG_PREFIX: ~/.npm-global
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install project npm deps
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
